### ISSUE TITLE
아카이브 메일에 서비스 링크 잘못 기입되어 있음

### ISSUE THREAD

**Issue by heli-os** [awesome-devblog/awesome-devblog#629]
http://daily-devblog.com/archive

<img width="351" alt="Screen Shot 2022-02-13 at 11 42 19 AM" src="https://user-images.githubusercontent.com/44586666/153735972-46580c04-f899-424c-b3d8-9a9cefd42e53.png">

하단 awesome-devblog 링크가 잘못되어 있습니다.

현재: https://awesome-devblog.herokuapp.com/
변경 필요: https://awesome-devblog.netlify.app/

**Comment by sarojaba** [comment]
안녕하세요.
언급하신 데일리 데브블로그는 어썸데브블로그의 데이터를 사용하는, 다른분이 운영하는 서비스입니다.
캡처하신 글에 문의방법이 있으니 그쪽으로 문의하시면 될것 같습니다.
아니면 대화방에 https://gitter.im/daily-devblog/community 남기셔도 될것 같네요.
