### ISSUE TITLE
노정우님의 블로그는 기술과 무관한 것 같습니다!

### ISSUE THREAD

**Issue by jaeyongjaykim** [awesome-devblog/awesome-devblog#665]
노정우
https://medium.com/@njw990

db 파일에 들어가있는데, 기술 블로그글이 아닌 내용들이 이메일로 전달됩니다.
하여, 제거가 필요하지 않을까 합니다!

**Comment by sarojaba** [comment]
제보 감사합니다.
이전에 기술 관련 포스팅들이 등록되었던 블로그인데, 최근에 경제 관련 글들이 많이 올라오네요.
기술 블로그라고도 볼 수 있고, 아니라고도 볼 수 있어, 판단하기 애매하네요.

이런 경우가 종종 있기 때문에, [어썸데브블로그](https://awesome-devblog.netlify.app/)의 경우에는 글의 카테고리로 필터링을 하고 있고, 말씀하신 글들은 수집 대상에서 제외되고 있어, 아직은 문제가 되지 않고 있습니다.
이메일에 관련된 것이라면, [Daily DevBlog](http://daily-devblog.com/)를 말씀하시는 것 같네요. 개발자분 메일이나 [Gitter](https://gitter.im/daily-devblog/community)를 이용해서 문의해보시면 좋을 것 같습니다. 제 생각에는 해당 서비스의 개발자분의 의견을 수용하는 것이 맞을 것 같네요.
