### ISSUE TITLE
HTTP 파라미터 변경을 통한 DOS 취약점 제보

### ISSUE THREAD

**Issue by mirusu400** [awesome-devblog/awesome-devblog#691]
https://awesome-devblog.netlify.app/korean/opensources?page=1&size=10

위를 포함한 인덱싱을 지원하는 많은 페이지에서 `size` 파라미터에 대한 검증이 적어도 1만까지는 없는 것으로 확인했습니다.

그렇기에, 큰 숫자를 넣은 경우에도 예외를 호출하지 않고 계속해서 쿼리를 진행하는 것 같습니다.

비동기를 이용해 1초에 몇십번씩 해당 크기를 조작해 전송을 보내면 비정상적인 부하와 더불어 방어시스템을 구축하지 않았다면 포트 고갈 문제도 발생할 듯 한데, 물론 그런 케이스는 없겠지만.. 확인해보시고 수정하시길 바랍니다. (직접 도와드리고 싶어도 해당 웹사이트 소스코드가 비공개인것 같아, 이슈로 남깁니다)

**Comment by sarojaba** [comment]
이슈 등록 감사드립니다.
개인적인 이유로 사이트 소스 코드를 비공개로 유지하는 점 양해 부탁드립니다.
