### ISSUE TITLE
페이지 리다이렉션 시 url 파라미터 제거

### ISSUE THREAD

**Issue by mirusu400** [awesome-devblog/awesome-devblog#692]
https://awesome-devblog.netlify.app/api/korean/people/feeds/view?url=https://gngsn.tistory.com/220

위와 같은 페이지를 통해 원본 블로그로 리다이렉션 시, url 파라미터를 유지한채로 리다이렉션 됩니다.

그럴일은 없겠지만, 리다이렉션 되는 페이지에서 url 파라미터를 사용한다면 문제가 될수도 있을 것 같아 이슈 남깁니다

**Comment by sarojaba** [comment]
이슈 등록 감사드립니다.

**Comment by sarojaba** [comment]
Nextjs의 동작인지, Netlify의 동작인지, redirect URL에 계속 이전 파라미터를 유지하네요. 중간중간 디버깅을 해봐도 코드상으로는 문제가 없는데, 계속 붙네요.
당분간 쉽게 고쳐지진 않을것 같습니다.

**Comment by sarojaba** [comment]
고쳤습니다.
