### ISSUE TITLE
RSS 업데이트 부탁드립니다

### ISSUE THREAD

**Issue by sonim1** [awesome-devblog/awesome-devblog#816]
https://github.com/awesome-devblog/awesome-devblog/pull/758

5월경에 위 PR을 생성하면서 블로그 주소 및 rss를 변경했는데, https://awesome-devblog.netlify.app/의 변경 전 rss주소를 사용중이라 새로운 글을  작성해도 피드에 보이지 않네요.

반영 부탁드리겠습니다 

감사합니다

**Comment by sarojaba** [comment]
안녕하세요.
확인해보니 수집은 잘 되고 있는 것 같습니다.
https://awesome-devblog.netlify.app/korean/people/feeds?author=%EC%A0%95%EB%B2%94%ED%9D%AC

단, 개인 목록은 버그가 있어, 현재 업데이트가 이뤄지지 않고 있습니다.
고쳐야 하는데 시간이 잘 안나네요. 양해 부탁드립니다.
